POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "MyBloghaha",
  "author": "Neil Ryan",
  "url": "www.nilblog.com",
  "likes": 9999
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/603b8936754136d166e31ca5

###
PUT  http://localhost:3003/api/blogs/603b8936754136d166e31ca7
Content-Type: application/json

{
  "title": "MyBffloghaha",
  "author": "Neiss Ryan",
  "url": "www.nilbsslog.com",
  "likes": 999933
}

